import { TanggalUlangTahun } from "./birthdayTypes";


export const birthdays: TanggalUlangTahun[] = [
    { date: new Date(1994, 8, 4), name: "Herlambang Wicaksono", message: "Happy Birthday, Herlambang!" },
    { date: new Date(2024, 8, 9), name: "Ester Sagala", message: "Happy Birthday, Kak Ester :)" },
    { date: new Date(2024, 8, 1), name: "Vero Puji", message: "Happy Birthday, Kak Vero Puji :)" },
    { date: new Date(2024, 8, 15), name: "dr. Maria Mayasari", message: "Happy Birthday, dr. Maria Mayasasri :)" },
    { date: new Date(2024, 8, 18), name: "dr. Endrotomo", message: "Happy Birthday, Kak dr. Endrotomo :)" },
    { date: new Date(2024, 8, 27), name: "Arlin", message: "Happy Birthday, Arlin :)" },
    { date: new Date(2024, 8, 21), name: "Claudia", message: "Happy Birthday, Claudia  :)" },
    { date: new Date(2024, 1, 31), name: "Tutut", message: "Happy Birthday, Kak Tutut :)" },
    { date: new Date(2024, 2, 3), name: "Veronica Sekar", message: "Happy Birthday, Kak Vero Sekar :)" },
    { date: new Date(2024, 2, 9), name: "dr. Astuti", message: "Happy Birthday, dr. Astuti :)" },
    { date: new Date(2024, 2, 6), name: "dr. Cosmas", message: "Happy Birthday, dr. Cosmas :)" },
    { date: new Date(2024, 2, 7), name: "dr. Felix", message: "Happy Birthday, dr. Felix :)" },
    { date: new Date(2024, 2, 16), name: "Bu Catrine", message: "Happy Birthday, Bu Catrine :)" },
    { date: new Date(2024, 2, 2), name: "dr. Erica", message: "Happy Birthday, dr.Erica :)" },
    { date: new Date(2024, 3, 14), name: "Hermansyah", message: "Happy Birthday, Hermansyah:)" },
    { date: new Date(2024, 3, 17), name: "Br. Patrick", message: "Happy Birthday, Br. Patrick :)" },
    { date: new Date(2024, 4, 2), name: "dr. Bagus", message: "Happy Birthday, dr. Bagus :)" },
    { date: new Date(2024, 4, 3), name: "Intan Pugel", message: "Happy Birthday, Kak Ina :)" },
    { date: new Date(2024, 4, 14), name: "Adithya", message: "Happy Birthday, Mas Adith :)" },
    { date: new Date(2024, 4, 16), name: "Novel", message: "Happy Birthday, Mbak Novel :)" },
    { date: new Date(2024, 4, 15), name: "dr. Irvan ", message: "Happy Birthday, dr. Irvan :)" },
    { date: new Date(2024, 4, 5), name: "April", message: "Happy Birthday, Mas April :)" },
    { date: new Date(2024, 4, 27), name: "dr. Yoan" , message: "Happy Birthday, dr. Yoan :)" },
    { date: new Date(2024, 3, 16), name: "HeriBertus", message: "Happy Birthday, Heribertus :)" },
    { date: new Date(2024, 5, 7), name: "kak Felice  dan Kak Ocha", message: "Happy Birthday, Kak Felice dan kak Ocha :)" },
    { date: new Date(2024, 5, 17), name: "dr. Odetta", message: "Happy Birthday, dr. Odetta :)" },
    { date: new Date(2024, 5, 11), name: "Nia", message: "Happy Birthday, Nia :)" },
    { date: new Date(2024, 6, 4), name: "br Dion", message: "Happy Birthday, br Dion :)" },
    { date: new Date(2024, 6, 21), name: "Andrea", message: "Happy Birthday, Kak Andrea :)" },
    { date: new Date(2024, 6, 18), name: "Yudi Herlangga", message: "Happy Birthday, bro Yudi Her :)" },
    { date: new Date(2024, 7, 1), name: "Jenny Elias", message: "Happy Birthday, Oma Jenny:)" },
    { date: new Date(2024, 7, 3), name: "Juliana Dolok", message: "Happy Birthday, Kak Butet :)" },
    { date: new Date(2024, 7, 9), name: "Kak Tasya dan Kristo", message: "Happy Birthday, Kak Tasya dan Kristo :)" },
    { date: new Date(2024, 7, 14), name: "dr. Ramzi", message: "Happy Birthday, dr. Ramzi :)" },
    { date: new Date(2024, 7, 16), name: "dr. Ivana", message: "Happy Birthday, dr. Ivana :)" },
    { date: new Date(2024, 9, 1), name: "Roosmawati dan dr.Timmy", message: "Happy Birthday, Bu Roosma dan dr.Timmy :)" },
    { date: new Date(2024, 9, 6), name: "dr. Edith", message: "Happy Birthday, dr. Edith :)" },
    { date: new Date(2024, 9, 7), name: "Susan Daton", message: "Happy Birthday, Kak Susan :)" },
    { date: new Date(2024, 9, 10), name: "Br. Wayan Subawe", message: "Happy Birthday, Bli Wayan :)" },
    { date: new Date(2024, 10, 10), name: "dr. Herbert dan Bu Jupe", message: "Happy Birthday, dr. Herbert dan Bu Jupe :)" },
    { date: new Date(2024, 10, 18), name: "Martina Okta", message: "Happy Birthday, Mbak Okta :)" },
    { date: new Date(2024, 12, 29), name: "Regi", message: "Happy Birthday, bang Regi :)" },

    // Tambahkan data ulang tahun lainnya di sini
];
